services:
  # Nacos 注册中心
#  nacos:
#    image: nacos/nacos-server:v2.3.2
#    container_name: nacos-Step
#    # 保持容器在没有守护程序的情况下运行
#    tty: true
#    restart: always
#    ports:
#      - "8848:8848"
#      - "9848:9848"
#      - "9849:9849"
#    environment:
#      - MODE=standalone
#      - JVM_XMS=256m
#      - JVM_XMX=256m
#      - JVM_XMN=128m
#    volumes:
#      - ./nacos/data:/home/nacos/data
#      - ./nacos/logs:/home/nacos/logs
#    networks:
#      - iot_network

  #postgresql 数据库
  postgresql:
    image: timescale/timescaledb:latest-pg17
    container_name: postgresql-Step
    # 保持容器在没有守护程序的情况下运行
    tty: true
#    restart: always
    privileged: true
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql17/data:/var/lib/postgresql17/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=zaohu279982
      - TZ=Asia/Shanghai
    networks:
      - iot_network

  # Redis 内存服务
  redis:
    image: redis:7.2-alpine
    container_name: redis-Step
    # 保持容器在没有守护程序的情况下运行
    tty: true
#    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis/conf/redis.conf:/etc/redis/redis.conf
      - ./redis/data:/data
    command: redis-server
    environment:
      - TZ=Asia/Shanghai
    networks:
      - iot_network

  # Sentinel 限流服务
  sentinel:
    image: bladex/sentinel-dashboard:1.8.6
    container_name: sentinel-Step
    # 保持容器在没有守护程序的情况下运行
    tty: true
#    restart: always
    ports:
      - "8718:8080"
    environment:
      - JAVA_OPTS=-Dserver.port=8080 -Dcsp.sentinel.dashboard.server=localhost:8080 -Dproject.name=sentinel-dashboard -Xms128m -Xmx128m
    networks:
      - iot_network

  # RocketMQ 服务
  rocketmq-namesrv:
    image: apache/rocketmq:5.3.1
    container_name: rocketmq-namesrv-Step
    # 保持容器在没有守护程序的情况下运行
    tty: true
#    restart: always
    ports:
      - "9876:9876"
    command: sh mqnamesrv
    volumes:
      - ./rocketmq/logs:/home/rocketmq/logs
      - ./rocketmq/store:/home/rocketmq/store
    networks:
      - iot_network

  rocketmq-broker:
    image: apache/rocketmq:5.3.1
    container_name: rocketmq-broker-Step
    tty: true
#    restart: always
    ports:
      - "10909:10909"  # SSL 端口（可选）
      - "10911:10911"  # 主端口
      - "10912:10912"  # 从端口（可选）
    command: sh mqbroker -c /opt/rocketmq/conf/broker.conf
    volumes:
      - ./rocketmq/broker/conf/broker.conf:/opt/rocketmq/conf/broker.conf
      - ./rocketmq/logs:/home/rocketmq/logs
      - ./rocketmq/store:/home/rocketmq/store
    environment:
      - JAVA_OPT_EXT=-Xms512m -Xmx512m -Xmn256m  # 限制 JVM 内存
      - BROKER_IP1=192.168.1.2
      - NAMESRV_ADDR=rocketmq-namesrv-Step:9876
#    extra_hosts:
#      - "namesrv:${NAMESRV_IP:-127.0.0.1}"  # 解决内部域名解析
    depends_on:
      - rocketmq-namesrv
    networks:
      - iot_network

  rocketmq-dashboard:
    image: apacherocketmq/rocketmq-dashboard:2.0.0
    container_name: rocketmq-dashboard-Step
    ports:
      - "8792:8080"
    environment:
      - JAVA_OPTS=-Drocketmq.namesrv.addr=rocketmq-namesrv-Step:9876 -Dserver.port=8080
    depends_on:
      - rocketmq-namesrv
      - rocketmq-broker
    networks:
      - iot_network

  # Elasticsearch
  elasticsearch:
    image: elasticsearch:8.17.4
    container_name: elasticsearch-Step
    tty: true
#    restart: always
    ports:
      - "9200:9200"  # 仅保留 HTTP 端口（禁用 HTTPS）
      - "9300:9300"  # 节点间通信端口
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m  # 限制 JVM 内存
      - xpack.security.enabled=false     # 禁用安全模块
      - xpack.security.transport.ssl.enabled=false  # 禁用节点间加密
      - xpack.security.http.ssl.enabled=false      # 禁用 HTTP 加密
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data  # 数据持久化
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml  # 挂载配置
    ulimits:
      memlock:
        soft: -1
        hard: -1  # 禁止内存交换，提高性能
    networks:
      - iot_network

  # Seata 全局事务管理
  seata:
    image: seataio/seata-server:2.0.0
    container_name: seata-Step
    tty: true
#    restart: always
    ports:
      - "8091:8091"  # Seata 服务端口
    environment:
      - SEATA_CONFIG_NAME=file:/root/seata-config/registry  # 配置文件路径
      - STORE_MODE=file  # 存储模式
      - SEATA_IP=seata  # 内部通信 IP（使用服务名）
    volumes:
      - ./seata/config:/root/seata-config  # 挂载配置目录
      - ./seata/logs:/seata-server/logs  # 挂载日志目录（可选）
#    depends_on:
#      - nacos  # 依赖 Nacos 注册中心
    networks:
      - iot_network

  emqx:
    image: emqx/emqx:5.4.1
    container_name: emqx-Step
    # 保持容器在没有守护程序的情况下运行
    tty: true
#    restart: always
    privileged: true
    ports:
      - "1883:1883"
      - "8083:8083"
      - "8883:8883"
      - "18083:18083"
    environment:
      - TZ=Asia/Shanghai
    volumes:
      # 挂载数据存储
      - ./emqx/data:/opt/emqx/data
      # 挂载日志文件
      - ./emqx/log:/opt/emqx/log
    networks:
      - iot_network

networks:
  iot_network:
    driver: bridge
